### ISSUE TITLE
How is it intended to install and use this project?

### ISSUE THREAD

**Issue by ctrlcctrlv** [cmdse/core#7]
I did:

```bash
export GOPATH=$HOME/.go
export PATH=$PATH:$GOPATH/bin
go install github.com/cmdse/core@latest
```

And got a binary named `core` in `$GOPATH/bin` not what I expected.

So I did

```bash
mv ~/.go/bin/core ~/.go/bin/cmdse
```

But the binary behaves oddly.

```go
$ cmdse --help
{ 
	pos:0,
	type:SemPOSIXShortSwitch,
	Value:'-l',
	BoundTo:<nil>,
	semCandidates:[]
}
{ 
	pos:1,
	type:SemPOSIXShortSwitch,
	Value:'-p',
	BoundTo:<nil>,
	semCandidates:[]
}
{ 
	pos:2,
	type:SemGNUSwitch,
	Value:'--only',
	BoundTo:<nil>,
	semCandidates:[]
}
{ 
	pos:3,
	type:SemOperand,
	Value:'argument',
	BoundTo:<nil>,
	semCandidates:[]
}
```

PS Thanks for the [useful grammar](https://cmdse.github.io/pages/appendix/bash-grammar.html), if nothing else!

**Comment by jsamr** [comment]
This was a hobby/research project for fun (and to discover go), it's not usable in a practical sense!
If you look at the main file, you'll see the hardcoded arguments:

https://github.com/cmdse/core/blob/2fb49535897b2dd483f5e5b3d15f002887bb269c/main.go#L8-L13

I should probably archieve this.

**Comment by ctrlcctrlv** [comment]
No problem, sorry, I could've just looked at the code yes but it's been years since I wrote any Go so I forgot how :laughing: 

Do you mind if I use your grammar in another project? I want to write a Bash→Rust transpiler that would allow people to quickly go from Bash script to compiled binary for performance reasons which do come up for me as I'm a Bash poweruser (a humorous thing to be yes).

**Comment by jsamr** [comment]
@ctrlcctrlv Of course! No problem. But note it's only V2 (and doesn't cover non US-ASCII encodings). Also, I'm not 100% sure of its origin, whether I got inspiration from a book or not, it dates a while back.
